# .github/workflows/java.yml
name: Java Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify Java installation
      run: |
        java -version
        javac -version

    - name: Compile Java code
      run: javac hello_world.java  # Compile hello_world.java

    - name: Run Java code with secret key
      run: |
        echo "Running Java program with secret key"
        java hello_world ${{ secrets.MY_SECRET_KEY }}  # Pass secret as command-line argument

    - name: Run HelloWorld Java program
      run: java hello_world  # Run the Java program
